name: Valid JSON

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run JSON validator
      run: python ./.github/scripts/valid_json.py airports.json
